apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  replicas: 5
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: pod
      labels:
        name: myapp
    spec:
      containers:
      - name: container1
        image: aanandi03/myimage
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
