apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    type: frontend
spec:
  containers:
  - name: container1
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP
        name: httpport
